config/routes.rb
Rails.application.routes.draw do


  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :sessions, only: :create
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'home#index'
  match 'auth/:provider/callback', to: 'sessions#createtwitter'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_create :confirmation_token
    has_secure_password
    
    validates :email, presence: true, uniqueness: true
    
    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end
    
    private
        def confirmation_token
          if self.confirm_token.blank?
              self.confirm_token = SecureRandom.urlsafe_base64.to_s
          end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
    def current_user
        @user ||= User.find(session[:user_id]) if session[:user_id]
    end
  helper_method :current_user
  
  private  
    def sign_in(user)
      
      session[:user_id] = user.id
      
    end  
  helper_method :sign_in      
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
  user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if user.email_confirmed
        sign_in user
        redirect_to root_path, notice: "Logged in!"
        #session[:user_id] = user.id
        #redirect_to root_url, notice: "Logged in!"
        else
        flash.now[:error] = 'Please activate your account by following the 
        instructions in the account confirmation email you received to proceed'
        render 'new'
      end
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def createtwitter
    raise env['omniauth.auth'].to_yaml
  end  
  
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        
        @user = User.new
        
    end
    
    def create
        
        @user = User.new(user_params)
        if @user.save
            
            UserMailer.registration_confirmation(@user).deliver
            flash[:success] = "Please confirm your email address to continue"
            redirect_to root_path
        else
            flash[:alert] = "OOps something went wrong...Please try again"
            render "new"
        end    
    end
    
    def confirm_email
        user = User.find_by_confirm_token(params[:id])
        if user
          user.email_activate
          flash[:success] = "Welcome to the Sample App! Your email has been confirmed.
          Please sign in to continue."
          redirect_to login_url
        else
          flash[:error] = "Sorry. User does not exist"
          redirect_to root_url
        end
    end
    
    private
        def user_params
            
            params.require(:user).permit(:email, :password, :password_confirmation)
            
        end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class= "container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end%>
    </div>
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to "Log Out", logout_path %>
    <% else %> 
      <%= link_to "Sign up", signup_path, class: 'btn btn-default' %> or
      <%= link_to "Log In", login_path, class: 'btn btn-default' %>
      <%= link_to "Sign in with Twitter", "/auth/twitter"%>
    <% end %>  
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>